CREATE USER db_admin
WITH PASSWORD 'admin';

GRANT ALL
ON ALL TABLES IN SCHEMA public
TO db_admin;

GRANT ALL
ON ALL SEQUENCES IN SCHEMA public
TO db_admin;

CREATE USER db_user
WITH PASSWORD 'user';

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO db_user;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO db_user;
